version: '3.8'

services:

  db:
    image: postgres:14.3
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES-PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      #PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: Examen
    volumes: 
      - ./postgres:/var/lib/postgresql/data